name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]
    types: [opened, synchronize]

jobs:
  test:
    name: CI Tests and Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # For pull_request_target, we need to checkout the PR head
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm format:check

      - name: Run tests
        run: pnpm test

      - name: Run tests with coverage
        run: pnpm test:coverage

      - name: Create act baseline if missing
        run: |
          if [ ! -f ".act-baseline.json" ]; then
            echo "Creating baseline for CI environment..."
            pnpm compatibility:baseline
          fi

      - name: Check act compatibility
        run: pnpm compatibility:check
